### model
model_name_or_path: /hpc2hdd/home/xxxs349/xxxc/huggingface/hub/qwen25-3B # 下面的save要一起改, 名字一般不变
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
lora_dropout: 0.1 # 数据量较小的时候开启
### dataset
dataset: ours_rea_miv_sft
template: llama3 # 我也不知道是不是用llama3的template，应该一样吧
cutoff_len: 20000
# max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4


### output
output_dir: saves/REA/MIV/ours/lora/sft-batch82
logging_steps: 100
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 1 # 2 tmd都设不了,性能退化3%
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 2.0 # lower, lr higher
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
#eval_dataset: qwen25-7B_mor_miii_sft_eval
# val_size: 0.1 # 划了0.1作为验证
#per_device_eval_batch_size: 1
#eval_strategy: steps
#eval_steps: 100000 # 500,一次性测完？

